### ISSUE TITLE
Finalize Project Topic

### ISSUE THREAD

**Issue by xinshizheng** [djfan/yelp-challenge#1]
Brainstorm and finalize project topic (Feb 20 - 26, 2017)

Yelp-Topic Choice:

 1. Find convergence duration (duration of time needed from opening on Yelp of the restaurant to its current star number— assuming star number truly reflects its business performance) 

    - duration. vs. location, culture, etc.  

2. Change of Expectation (biz star vs individual star)

    - change vs. factors — feature selection, 

3. Yelp Business v.s. Health Validation Rate 

    - Predict HVR using Yelp user reviews

**Comment by djfan** [comment]
**Choice 3**

*Related Websites*
- [Data Science Challenge: Predict Restaurant Health Scores with Yelp Data](https://www.yelpblog.com/2015/06/data-science-challenge-predict-restaurant-health-scores-with-yelp-data)
- [Keeping it Fresh: Predict Restaurant Inspections](https://www.drivendata.org/competitions/5/keeping-it-fresh-predict-restaurant-inspections/page/28/)

**Comment by xinshizheng** [comment]
Choice 1 is not realistic since there is no time series for review and scores.

**Comment by djfan** [comment]
Here is original idea, it's a project report of cs229! [Predicting International Restaurant Success with Yelp](http://cs229.stanford.edu/proj2016spr/report/062.pdf)

Besides, that's the one I shared with you through email. [Information Extraction from Social Media for Public Health](http://web3.cs.columbia.edu/~gravano/Papers/2014/kdd2014.pdf)

**Comment by djfan** [comment]
IDEA:
I think everybody need to do more **_paper reviews._**
Let's share the paper you've read here. ( 2-3 for each of us @xinshizheng @kayzhou22 )  
Think about the **interpretability** and **feasible** .
