### ISSUE TITLE
Identify Best Database Practices

### ISSUE THREAD

**Issue by xinshizheng** [djfan/yelp-challenge#3]
Identify a good database platform and understand how to utilize for this project.
1. databases:   (free platforms for small project)
[Options for downloading](http://alternativeto.net/software/microsoft-sql-server/?platform=mac)
           MS SQL Server Express (Windows only....)
           SQLite (easy to install) 
2. Create index & Link Data Sets

**Comment by djfan** [comment]
quite interested in: 

- [ ] PostgreSQL 
- [ ] MongoDB
- [ ] MySQL Community Edition

- [ ] **SQLite**

**Comment by djfan** [comment]
If necessary, I'd like to do with **_AWS_** stuff? @kayzhou22 

Besides, I'm not sure is there any great tool to simply **viz the structure&relationship of the database** (for publish or presentation). Maybe useful in the future. I think we can keep an eye on this challenge.
